// TO DO
// FRAME COUNTER
// METRONOME
// CHAR ROSETTA STONE
// OBJECT TO STORE CURRENT GLYPHS ON BOARD?
// HAVE PARSER TO READ GLYPHS ON BOARD IN REAL TIME?




// SET UP MIDI CLIENT
// SEND 